### PR TITLE
Pick special floor config

### PR DESCRIPTION
**Pull request by FredericF-IT**
Added config to choose special floor

### CODE REVIEW

**Review by Sykander — COMMENTED** [review]
In regards to this - it was planned to add `requirements` onto special floors r(equirements that need to be fulfilled for the special floor to be possible eg. for a shopkeeper to show then the shopkeeper npc needs to be alive) and to make special floors dynamic to dungeon data (eg. a special floor could read in the list of adventurers and address one specifically)

I am not sure how that would mesh with this server config functionality added in this PR

Perhaps we could implement that functionality first and then this PR? (totally happy for you to do it in this PR too)

**Comment by FredericF-IT** [comment]
Sure, so just a new field for each room?
And get_special_floor_list would check those and only return those that meet the requirements?

**Comment by Sykander** [comment]
Yeah exactly

It'd also involve checking if the fields on the floors were strings or callable functions - and if they are callable they should take the dungeon data as a param and return a string which we then use in the dungeon

**Comment by Sykander** [comment]
```
{
  "name: "Shopkeeper",
  "desc": lambda dungeon_data: f'**Shopkeeper**: "Hello again {dungeon_data["adventurers"][0]}! Interested in buying 3 health potions for 50 gp each?"',
  "requirements": lambda dungeon_data: not dungeon_data["npcs"]["shopkeeper"]["dead"]
} 
```

**Pull request closed without merging**
